add geologicalProject
SameerAlHarbi/sgs-khadamati-sap pull request #10
Opened 2022-03-09 07:14 UTC by OsamaNajjar

dear @SameerAlHarbi 

please reviw new code for geological Projects

2022-03-09 14:55 UTC, SameerAlHarbi commented on src/routers/delegations.router.js
> +// /delegations/geologicalProject => POST body {"projectCode": "000011",
// /delegations/projects => POST body {"projectCode": "000011",

2022-03-09 14:55 UTC, SameerAlHarbi commented on src/routers/delegations.router.js
> +Router.post('/geologicalProject', geologicalProjectsController.addOrEditGeologicalProject);
Router.post('/projects', geologicalProjectsController.addOrEditGeologicalProject);

2022-03-09 14:57 UTC, SameerAlHarbi commented on src/routers/delegations.router.js
> +//                                              "projectYear": "2022",
// "year": "2022",

2022-03-09 15:27 UTC, SameerAlHarbi commented on src/controllers/geological-projects.controller.js
> +const geologicalProjectsManager = require('../managers/geological-projects.manager');
const projectsManager = require('../managers/projects.manager');

2022-03-09 15:29 UTC, SameerAlHarbi commented on src/controllers/geological-projects.controller.js
> +exports.addOrEditGeologicalProject = async (req, res, next) => {
exports.saveProject = async (req, res, next) => {

2022-03-09 15:30 UTC, SameerAlHarbi commented on src/controllers/geological-projects.controller.js
> +    const geologicalProject = req.body;
const project = req.body;

2022-03-09 16:29 UTC, SameerAlHarbi requested changes
Please review this changes

2022-03-09 16:29 UTC, SameerAlHarbi commented
Please pull this branch before change

2022-03-10 06:34 UTC, OsamaNajjar commented
Please review new code for Projects

2022-03-13 11:59 UTC, merged