6 delegations types
SameerAlHarbi/sgs-khadamati-sap pull request #7
Opened 2022-02-28 07:31 UTC by OsamaNajjar

Dear @SameerAlHarbi 
Delegatings Types done
Plaese check and aprove pull requast

2022-02-28 15:50 UTC, SameerAlHarbi requested changes

2022-03-01 04:59 UTC, OsamaNajjar commented on src/routers/delegations.router.js
> +Router.get('/delegationsTypes', delegationsController.getDelegationsTypes);
done

2022-03-01 05:01 UTC, OsamaNajjar commented on src/managers/delegations.manager.js
> + exports.getDelegationsTypes = async (lang = 'A') => {
done

2022-03-01 05:01 UTC, OsamaNajjar commented on src/controllers/delegations.controller.js
> +exports.getDelegationsTypes = async (req, res, next) => {
done

2022-03-01 05:03 UTC, OsamaNajjar commented on src/controllers/delegations.controller.js
> +            .getDelegationsTypes(lang);
done

2022-03-01 06:26 UTC, SameerAlHarbi commented
merge to development

2022-03-01 06:26 UTC, closed without merging